requirements		= (OpSysAndVer == "CentOS7")
getenv			= True
executable              = CARLPreprocess.sh
arguments               = $(argument)
output                  = CARLRun.$(ClusterId).$(ProcId).out
error                   = CARLRun.$(ClusterId).$(ProcId).err
log                     = CARLRun.$(ClusterId).log
request_memory 		= 60000 MB
should_transfer_files   = YES
+JobFlavour             = "tomorrow"
queue