requirements		= (OpSysAndVer == "CentOS7")
getenv			= True
executable              = CARLRunFlavours.sh
arguments               = $(ClusterId)$(ProcId)
output                  = CARLRun.$(ClusterId).$(ProcId).out
error                   = CARLRun.$(ClusterId).$(ProcId).err
log                     = CARLRun.$(ClusterId).log
should_transfer_files   = YES
+JobFlavour             = "testmatch"
request_memory 		= 40000 MB
request_GPUs 		= 1
request_CPUs 		= 0
queue